### PR TITLE
Add mean property for distribution value

### PR DESCRIPTION
**Pull request by marianhromiak**
This PR only add missing "mean" property which is missing in SD distribution value.

### CODE REVIEW

**Comment by c24t** [comment]
Hey @marianhromiak, thanks for the PR. The change LGTM, I changed some tests in dc3a0134 such that they'll fail without this change.

@lzchen (and cc @aabmass) I see that you removed these tests in #905, we'll need them back to merge this PR.

**Comment by c24t** [comment]
@marianhromiak please sign the CLA.

**Comment by lzchen** [comment]
@c24t 
stackdriver tests were failing builds for some reason. I believe those have to be resolved first before merging the PR.

**Comment by aabmass** [comment]
Sorry, I'll look into those tests first thing tomorrow!

**Pull request merged**
