### PR TITLE
Log a more useful message when an integration fails to load

### PR DESCRIPTION
**Pull request by benjaminjkraft**
The error was being swallowed, which made it more difficult than
necessary to understand what was wrong when I ran into #210.

### CODE REVIEW

**Comment by reyang** [comment]
@benjaminjkraft `config_integration` has been refactored in https://github.com/census-instrumentation/opencensus-python/commit/26fd836a8ae4e38493ef70862ab2baee6ced2339. I believe by logging the module namespace and the actual exception/callstack, we should have sufficient information for troubleshooting.

I would like to get your feedback, do you think we should provide more info?
I will close this PR for now, please feel free to reopen and work on the improvements. I can help to review and merge it.

@c24t for awareness.

**Comment by benjaminjkraft** [comment]
Oops, I never realized this hadn't been merged.  Anything that logs the error is good enough for us!

**Comment by reyang** [comment]
@benjaminjkraft would you look at https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/config_integration.py#L36 and confirm if this is good for your scenario?

**Comment by benjaminjkraft** [comment]
Yeah that seems fine!

**Comment by reyang** [comment]
Thanks @benjaminjkraft!

**Pull request closed without merging**
