### PR TITLE
Enforce str for some django attributes

### PR DESCRIPTION
**Pull request by geobeau**
Some attributes were of type unicode

### CODE REVIEW

**Comment by geobeau** [comment]
CC: @c24t

**Comment by c24t** [comment]
LGTM, but I'm curious what error you see with unicode attributes. Maybe we should enforce `str`s in `add_attribute`.

**Comment by geobeau** [comment]
A log saying the attribute couldn't be encoded. Maybe we can accept unicode type and cast it as str.

**Comment by geobeau** [comment]
Ah it was coming from Jaeger exporter: https://github.com/census-instrumentation/opencensus-python/blob/b3c298f696108feb7f134b0c5ebdaf1fff8939df/opencensus/trace/exporters/jaeger_exporter.py#L298

**Pull request merged**
