### PR TITLE
Update default python version to 3.7

### PR DESCRIPTION
**Pull request by c24t**
Add python 3.7 to supported versions, run unit and system tests against 3.7, and update our default CI target version to 3.7.

### CODE REVIEW

**Comment by reyang** [comment]
@zoidbergwill FYI

**Comment by c24t** [comment]
The default travis base image doesn't support 3.7, so we need to explicitly require ubuntu 16.04. See https://github.com/travis-ci/travis-ci/issues/9069 and https://github.com/travis-ci/travis-ci/issues/9815.

**Comment by c24t** [comment]
Our old circle base image ([googleapis/nox](https://hub.docker.com/r/googleapis/nox/)) doesn't support 3.7. I've changed this to [googleapis/python-multi](https://hub.docker.com/r/googleapis/python-multi), but we may want to update the nox image instead.

**Comment by c24t** [comment]
The new circle image doesn't include openssl, looks like we need to update the old image or start using one of our own.

**Comment by zoidbergwill** [comment]
Not sure where the source is for the nox image, but we should probably update it to a newer version of nox too. Seems like some things have changed when fiddling with it for my PR

**Comment by reyang** [comment]
@lzchen is working on #402.

**Comment by reyang** [comment]
Python 3.7 support has been added by #665.
Although we are still in progress of retiring Circle CI, we already got Python 3.7 test covered by Travis CI.

**Pull request closed without merging**
