### PR TITLE
Hotfix/django flask pyramid status code

### PR DESCRIPTION
**Pull request by victoraugustolls**
Updating `http.status_code` to be an int, as discussed with @reyang. This affects the following contributions:
- Django
- Flask
- Httplib
- Pyramid

### CODE REVIEW

**Comment by reyang** [comment]
I haven't taken a deep look into the system test failures. It seems some of the system tests are looking for span labels instead of attributes, and label value is always string.

**Comment by victoraugustolls** [comment]
I can update the tests to get the attributes instead, if possible!

**Comment by reyang** [comment]
I haven't done the archaeology, would be curious to understand why we had labels instead of attributes in the first place.

**Comment by victoraugustolls** [comment]
Who might know this? And is this a block for merging? If so, I can either swap for attributes or try to understand why we are using labels!

**Comment by reyang** [comment]
I don't think it's blocking unless @c24t says otherwise.

**Comment by victoraugustolls** [comment]
Waiting for his input so, and if is a block, I would please ask if @c24t can give an explanation of why we are using labels and if there is any workaround!

**Comment by victoraugustolls** [comment]
@c24t any comments here?

**Comment by victoraugustolls** [comment]
Pinging @c24t, if there are no responses, should we merge @reyang ?

**Comment by reyang** [comment]
@victoraugustolls sorry for my delayed response. We can move forward by changing the test cases to use attributes instead of labels. Once the CI passed, we're good to merge.

**Comment by victoraugustolls** [comment]
Will update later today!

**Comment by victoraugustolls** [comment]
> @victoraugustolls sorry for my delayed response. We can move forward by changing the test cases to use attributes instead of labels. Once the CI passed, we're good to merge.

As we are using google cloud spans that does not contain `attributes`, only `labels`, this is not possible. The strangest thing to me is that in the stackdriver exporter tests, it was already expecting an int as status code, but it was receiving an string before my changes. I could add an special case for the stackdriver exporter where status code would be converted from int  to string, but don't know if this is desired. What do you think @c24t @reyang ?

**Comment by reyang** [comment]
> The strangest thing to me is that in the stackdriver exporter tests, it was already expecting an int as status code, but it was receiving an string before my changes. I could add an special case for the stackdriver exporter where status code would be converted from int  to string, but don't know if this is desired. What do you think @c24t @reyang ?

@c24t @songy23 Looks like int should be the correct answer:
* https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/trace_exporter/__init__.py#L253
* https://cloud.google.com/trace/docs/reference/v2/rest/v2/Status

**Comment by victoraugustolls** [comment]
@songy23 and what about the failing system tests?

**Comment by victoraugustolls** [comment]
A course of action is needed here, system tests fails but the changes were approved. @c24t @songy23 @reyang

**Comment by reyang** [comment]
It seems that Stackdriver labels are always strings. @victoraugustolls would the system test pass if you convert status from int to str in the Stackdriver exporter?

**Comment by victoraugustolls** [comment]
Google client only accepts labels as strings due to the proto format, and during the conversion inside the client, it loses the status code. If I transform the status code to string, it would work, but wouldn’t be “right”. But I think this could be tracked in another issue so we can move this forward!

**Comment by victoraugustolls** [comment]
@c24t @songy23 @reyang added tests to see if status code was being converted correctly, but still not enough for the system tests. Can someone take a look?

**Comment by victoraugustolls** [comment]
Merged @reyang solution, thanks for the help!
@songy23  @c24t  we are receiving `429` from Google Client here, any tips?

**Pull request merged**
