### PR TITLE
#279 Add new method to set span status.

### PR DESCRIPTION
**Pull request by maeserichar**
Just an easy change to avoid needing to import status in order to set the status of a span.

### CODE REVIEW

**Comment by victoraugustolls** [comment]
This was partially discussed [here](https://github.com/census-instrumentation/opencensus-python/pull/738#discussion_r309378259)!

@reyang What do you think?

**Comment by lzchen** [comment]
With this change, is there a need for the `Status` class?
What do you think @victoraugustolls  @reyang ?

**Comment by victoraugustolls** [comment]
This seems to me more like a helper method, and I wouldn't remove `Status` class, as not only it is a breaking change but is referenced in `OT` spec as mandatory, and it would make the job a lot difficult in the migration in case it was removed.

In my opinion, I would rather have utils method and not add it inside the `Span` class, but it is a personal view, would wait @reyang for comments.

**Comment by reyang** [comment]
I agree with @victoraugustolls.

**Comment by maeserichar** [comment]
Great! So something in the line of `setSpanStatus(span, code, message, details)` in `trace/utils.py' would be more aligned with that?

**Pull request closed without merging**
