### PR TITLE
Correct association of spans with trace for StackdriverExporter - Fixes #212

### LINKED ISSUE #212: StackdriverExporter with BackgroundThreadTransport  will use wrong trace_id
This diff fixes the issue: 

index 22a09e7..50cefa0 100644
--- a/opencensus/trace/exporters/stackdriver_exporter.py
+++ b/opencensus/trace/exporters/stackdriver_exporter.py
@@ -14,6 +14,7 @@
 
 import os
 
+from collections import defaultdict
 from google.cloud.trace.client import Client
 
```
 from opencensus.trace import attributes_helper
@@ -146,10 +147,14 @@ class StackdriverExporter(base.Exporter):
 
         # convert to the legacy trace json for easier refactoring
         # TODO: refactor this to use the span data directly
-        trace = span_data.format_legacy_trace_json(span_datas)
 
-        stackdriver_spans = self.translate_to_stackdriver(trace)
-        self.client.batch_write_spans(name, stackdriver_spans)
+        trace_id_sds = defaultdict(list)
+        for sd in span_datas:
+            trace_id_sds[sd.context.trace_id] += [sd]
+        for _, sds  in trace_id_sds.items():
+            trace = span_data.format_legacy_trace_json(sds)
+            stackdriver_spans = self.translate_to_stackdriver(trace)
+            self.client.batch_write_spans(name, stackdriver_spans)
 
     def export(self, span_datas):
         """
```

Without this patch, the span_data.format_legacy_trace_json method will take the trace_id of the first span_data. But when using a BackgroundThreadTransport we'll be writing multiple span_data objects in batches perhaps from multiple requests and trace_ids.   

Thanks for correcting.

### PR DESCRIPTION
**Pull request by ocervell**
See original issue #212 for details.

### CODE REVIEW

**Comment by ocervell** [comment]
@liyanhui1228 any updates here ? this is seriously tampering with how traces show on tracing interfaces.

**Comment by liyanhui1228** [comment]
LGTM, will merge once the CI passes.

**Comment by liyanhui1228** [comment]
@ocervell Do you need me to do a new release for this today?

**Comment by ocervell** [comment]
Yes, but I think next release should also integrate https://github.com/census-instrumentation/opencensus-python/pull/297 otherwise the exporter can crash the BackgroundThreadTransport

**Pull request merged**
