### PR TITLE
Check that url_rule is not None before dereferencing property

### LINKED ISSUE #777: Flask middleware raises AttributeError for 404 routes
**Describe your environment.** 
Python 3.7, Flask 1.1, OpenCensus 0.7.3

**Steps to reproduce.**
1. Run opencensus with the Flask middleware enabled with any Flask app
2. Hit a URL that does not map to a rule (ie. `/foo`)

**What is the expected behavior?**
Don't expect exceptions thrown for 404 routes

**What is the actual behavior?**
Every 404 route is generating exceptions

**Additional context.**

The problem is caused by the following PR: https://github.com/census-instrumentation/opencensus-python/pull/759

It assumes that the url_rule is not None -- if you hit any non-existent URL (ie. a 404-triggering URL), then `request.url_rule` will be None and code will raise an `AttributeError`

### PR DESCRIPTION
**Pull request by jtbeach**
Fixes #777

### CODE REVIEW

**Comment by jtbeach** [comment]
@googlebot I signed it!

**Comment by olance** [comment]
@jtbeach you should improve the tests I had provided for the `HTTP_ROUTE` attribute, to add one that specifically tests a non-existing route.

Happy to help if needed!

**Comment by jtbeach** [comment]
@olance @reyang I think this is now ready for review

**Comment by reyang** [comment]
Thanks @jtbeach and @olance!

**Comment by jtbeach** [comment]
@reyang Any idea when a release will be made with this fix?

**Comment by lzchen** [comment]
@jtbeach 
https://github.com/census-instrumentation/opencensus-python/releases/tag/v0.7.5

**Pull request merged**
