### PR TITLE
remove sqlalchemy upper limit version

### PR DESCRIPTION
**Pull request by lwatskot**
https://github.com/census-instrumentation/opencensus-python/issues/1139

### CODE REVIEW

**Comment by javier-martinez-codurance** [comment]
@hectorhdzg Hi, brief question do you know if the upper limit was there for a reason? I would like to add the extension but due to this constraint I can not do it properly. Thanks in advance!

**Comment by lwatskot** [comment]
@hectorhdzg @lzchen can you please take a look at this?

**Comment by aberres** [comment]
Getting this merged would be great!

**Comment by panteamihai** [comment]
@hectorhdzg @lzchen @aabmass could you guys please take a look at this?

**Review by aabmass — APPROVED** [review]
Thanks for the PR and apologies for the slow response.

It looks like SQLAlchemy doesn't support python 3.4 anymore at all. https://github.com/sqlalchemy/sqlalchemy/blob/main/setup.cfg#L34. I think this change is fine as it is the user's responsiblity to pin the correct version of SQLAlchemy for their python interpreter version.

**Review by lzchen — APPROVED** [review]

**Pull request merged**
