### PR TITLE
span context: set the default recorded flag to 0, and fix default trace options bug

### LINKED ISSUE #159: Missing support for "forced tracing"
I think you use the trace options from StackDriver incorrectly, based on this:
https://cloud.google.com/trace/docs/support?hl=sr#how_do_i_force_a_request_to_be_traced

`o=1` should mean forced tracing, regardless of the decision of the sampler. So here:

https://github.com/census-instrumentation/opencensus-python/blob/cfcfda584ba984e6f0e89684120c1ea94271b2c9/opencensus/trace/tracer.py#L68-L77

you should probably say `or` instead of `and` but please correct me if I'm missing something. To me it's more intuitive from a developer POV to have a way to force tracing for debugging reasons when needed and otherwise use some constant sampling rate. And maybe I would rename `enabled` to `forced`. I'm happy to open PR ofc if this makes sense by first look to you

### LINKED ISSUE #298: All samplers are ignored as the default span context is force enabled
Since #159 was merged, sampler decisions are ignored (even AlwaysOffSampler) as the default span context is force enabled. It intended to solve a valid use-case but now every span context is force enabled. Unless you manually send a span context with `o=0`.

A quick and dirty solution could be changing `trace_options.DEFAULT` and `span_context.DEFAULT_OPTIONS` to `'0'`. Better yet, the default context should set `o` to `int(sampler.should_sample(...))`. However, neither solves that `o=0` does not disable tracing.

### PR DESCRIPTION
**Pull request by wsabransky**
Closes #298 .

Currently, the default trace option for a new trace context is to set `enabled` to true. This causes all samplers applied to be ignored [here](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/tracer.py#L76). We should keep the parent sampling decision if it is true, but ignore it if false. A parent shouldn't be able to force a downstream service to not sample.

Also fixes bug described [here](https://github.com/census-instrumentation/opencensus-python/pull/474#issuecomment-469915775).

### CODE REVIEW

**Comment by songy23** [comment]
Please rebase and fix lint.

**Comment by songy23** [comment]
> The lint error appears to be wholly unrelated to this PR, in a file not touched. Do you want it fixed in this change?

I see, For some reason lint didn't fail on my local machine. For now please ignore the error and just rebase against master.

**Comment by bogdandrutu** [comment]
@wsabransky any chance we can get some tests :)

**Comment by wsabransky** [comment]
@bogdandrutu @c24t Sorry about the delay, I'll add some tests today.

**Comment by wsabransky** [comment]
@c24t @bogdandrutu Okay, apparently there were already tests that cover this case, but they weren't included by the test runner because of how they were named.

Additionally, a scoping problem was causing the default trace options to be overwritten at runtime in some cases.

**Comment by wsabransky** [comment]
@c24t any chance we could get this merged?

**Comment by c24t** [comment]
@wsabransky it looks like this change breaks a jaeger integration test. I may have time to check it out later, but it can't merge as-is.

**Comment by wsabransky** [comment]
@c24t looks like it was just a fixture that needed to be updated to reflect the new behavior in this PR. I've made the change.

**Comment by c24t** [comment]
Thanks @wsabransky!

**Pull request merged**
