### PR TITLE
refactor - move header name to propagator (part 2)

### LINKED ISSUE #167: Trace header should be tied to propagator and not web framework
for example: https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/ext/flask/flask_middleware.py#L34

This is related to https://github.com/census-instrumentation/opencensus-python/issues/46#issuecomment-384423270

### PR DESCRIPTION
**Pull request by reyang**
Fix #167

### CODE REVIEW

**Comment by reyang** [comment]
@liyanhui1228, is this a transient failure while running system test? Would you help to trigger the CI? Thanks!

**Comment by reyang** [comment]
@liyanhui1228, would you help to look in to the CI error?
I can look into the issue if there a way to reproduce them on my local environment - do you have instructions on how to run system test locally?

**Comment by SergeyKanzhelev** [comment]
I created a work item to track contributing.md update: https://github.com/census-instrumentation/opencensus-python/issues/224

**Comment by kornholi** [comment]
Hi @reyang, the CI failures are actually valid because of how Django works.

In `request.META`, all incoming headers are prefixed with `HTTP_`, so `X-Cloud-Trace-Context` gets stored as `HTTP_X_CLOUD_TRACE_CONTEXT` instead of `X_CLOUD_TRACE_CONTEXT`.

I think the best solution here is to wrap `request.META` with an object where `__getitem__` rewrites the key `X-Foo` to `HTTP_X_FOO`, then pass that object into `from_headers`. What do you think?

**Comment by reyang** [comment]
@kornholi, I see, thanks for the hint!
I agree with the your suggestion, let me make the code change now.

**Comment by kornholi** [comment]
@liyanhui1228 PTAL. I will refactor the Zipkin/B3 PR after this is in.

**Pull request merged**
