### PR TITLE
grpc client interceptor should set current span back to previous one in _callback

### PR DESCRIPTION
**Pull request by tjzo**
Client interceptor called execution_context.set_current_span(current_span) in _start_client_span, and called execution_context.set_current_span(current_span) in _callback again, so the previous span(maybe root span) was missing, and jaeger displayed as trace-without-root-span. I thought it should record the previous span and set it back in _callback function.

### CODE REVIEW

**Comment by tjzo** [comment]
I signed it!

**Comment by tjzo** [comment]
I signed it!

**Comment by reyang** [comment]
@tjzo please take a look at #539.

**Comment by tjzo** [comment]
Thanks @reyang! this commit can fix the same issue.

**Pull request closed without merging**
