### PR TITLE
New style middleware

### PR DESCRIPTION
**Pull request by mhindery**
Since old Django versions are not supported anymore (https://github.com/census-instrumentation/opencensus-python/pull/694), move the middleware to the new style ([Django docs on it](https://docs.djangoproject.com/en/2.2/topics/http/middleware/#writing-your-own-middleware)). This simplifies the code somewhat, since variables are now in one scope of the `__call__` method, and there's less of the util functions required which were there to access these variables previously across `process_request` / `process_view` / `process_request` via the thread local context.

I've made the `set_django_attributes` method public one, as it is useful for people to have the option to easily set their own custom properties apart from the ones used by default.

@timgraham @reyang

### CODE REVIEW

**Comment by timgraham** [comment]
Old-style middleware are deprecated but supported in Django 1.11 (if using the old MIDDLEWARE_CLASSES setting rather than the new MIDDLEWARE setting). I would delay this change until Django 1.11 end of life. Typically when the next Django LTS is released (Django 2.2 in December 2019), then it's a good time to remove support for older versions of Django.

**Comment by reyang** [comment]
@mhindery I'm closing the PR based on what @timgraham mentioned. Please reopen it once Django 1.11 reached end of life. Thanks.

**Comment by mhindery** [comment]
I would like to pick this up again. However, it looks to be better at this point to invest in an opentelemetry implementation as that is the successor of the project. There does not seem to be a Django implementation available yet (looking at https://opentelemetry-python.readthedocs.io/en/stable/index.html) Would the project be open to that, if so I would be willing to have a look at that?

**Comment by lzchen** [comment]
@mhindery 
Yes there is not Django integration yet for OpenTelemetry. Feel free to contribute to the OT-python [repo](https://github.com/open-telemetry/opentelemetry-python)! We already have a [flask](https://github.com/open-telemetry/opentelemetry-python/tree/master/ext/opentelemetry-ext-flask) integration leveraging the [wsgi](https://github.com/open-telemetry/opentelemetry-python/tree/master/ext/opentelemetry-ext-wsgi) integration so you can refer to those.

**Comment by mhindery** [comment]
I've started an PR on https://github.com/open-telemetry/opentelemetry-python/pull/571, so I won't develop this one any further.

**Pull request closed without merging**
