### PR TITLE
SD exporter and set_status release

### PR DESCRIPTION
**Pull request by c24t**
#749 as applied to master.

### CODE REVIEW

**Comment by reyang** [comment]
Do we need to release/update `opencensus-ext-ocagent`?

**Comment by victoraugustolls** [comment]
Should it include `pymongo` release and [upcoming](https://github.com/census-instrumentation/opencensus-python/pull/746) `requests` release into this one too?

**Comment by c24t** [comment]
> Do we need to release/update `opencensus-ext-ocagent`?

It looks like it, in the future let's include a changelog line for changes that require a new release of the ext package

> Should it include `pymongo` [release](https://github.com/census-instrumentation/opencensus-python/pull/738) and [upcoming](https://github.com/census-instrumentation/opencensus-python/pull/746) `requests` release into this one too?

Let's save the others for another release.

**Comment by victoraugustolls** [comment]
> Let's save the others for another release.

Okk, just a reminder that `pymongo` changes are included in the same [PR](https://github.com/census-instrumentation/opencensus-python/pull/738) as `set_status` addition!

**Comment by c24t** [comment]
Thanks, I got the `pymongo` changes in 0acdd38 on the release branch, I'll cherry pick them here.

**Pull request merged**
